storage: ./storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  'serverless-esbuild-layers':
    access: $all
    publish: $anonymous
  '**':
    access: $all
    proxy: npmjs
